# Change these first
owner: cloudpanda
repo: uptime # The name of this repository

sites:
  - name: Games
    url: https://games.cloudpanda5.repl.co/

status-website:
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Hello"
  introMessage: This is a status site.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
